{{ config(schema='DATALAKE') }}

Select
    USER_ID
    , TRANSACTION_ID
    , ACCOUNT_ID
    , ACCOUNT_CREATED_AT
    , ACCOUNT_TYPE
    , ACCOUNT_SUB_TYPE
    , CATEGORY_MCC
    , TRANSACTION_TYPE
    , NAME
    , DROP_MAPPED_BRAND_NAME
    , TRANSACTION_AMOUNT
    , TRANSACTION_DATE
    , TRANSACTION_CREATED_AT
    , TRANSACTION_UPDATED_AT
    , IS_PENDING
    , PENDING_TRANSACTION_ID
    , ACCOUNT_INSTITUTION_NAME
    , LOCATION_STATE
    , LOCATION_CITY
    , LOCATION_ZIP
    , LOADED_AT
    , FIRST_LOADED_AT
From
    {{ source('SNOWFLAKE_SALES_DEMO','TRANSACTIONS')}}
