{{ config(schema='DWH') }}

Select
    USER_ID
    , TRANSACTION_ID
    , ACCOUNT_ID
    , CATEGORY_MCC
    , TRANSACTION_TYPE
    , MERCHANT_NAME
    , DROP_MAPPED_BRAND_NAME
    , TRANSACTION_AMOUNT
    , TRANSACTION_DATE
    , TRANSACTION_CREATED_AT
    , TRANSACTION_UPDATED_AT
    , CLIENT_NAME
    , STATE
    , CITY
    , ZIP
    , LOADED_AT
    , FIRST_LOADED_AT
From
    {{ source('STAGINGAREA', 'STGVALIDUSERTRANSACTIONS') }}