{{ config(schema='STAGINGAREA') }}

Select
    TX.USER_ID
    , USR.CUSTOMERNAME
    , TX.TRANSACTION_ID
    , TX.ACCOUNT_ID
    , TX.ACCOUNT_CREATED_AT
    , TX.ACCOUNT_TYPE
    , TX.ACCOUNT_SUB_TYPE
    , TX.CATEGORY_MCC
    , TX.TRANSACTION_TYPE
    , TX.NAME As MERCHANT_NAME
    , TX.DROP_MAPPED_BRAND_NAME
    , TX.TRANSACTION_AMOUNT
    , TX.TRANSACTION_DATE
    , TX.TRANSACTION_CREATED_AT
    , TX.TRANSACTION_UPDATED_AT
-- We're excluding PENDING transactions (for the sake of this PoC)
--    , TX.IS_PENDING
--    , TX.PENDING_TRANSACTION_ID
    , TX.ACCOUNT_INSTITUTION_NAME AS CLIENT_NAME
    , TX.LOCATION_STATE AS STATE
    , TX.LOCATION_CITY AS CITY
    , TX.LOCATION_ZIP AS ZIP
    , TX.LOADED_AT
    , TX.FIRST_LOADED_AT
From
    {{ source('DBT_Processing', 'RAWINGESTION_TRANSACTIONS') }} TX
    Inner Join
    {{ source('STAGINGAREA', 'TBLCUSTOMERS') }} USR 
        on TRIM(TX.USER_ID) = TRIM(USR.CUSTOMERID)

-- We're excluding PENDING transactions (for the sake of this PoC)
Where
    Not IS_PENDING
